name: Deploy Hub

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: pairs
      #     path: pairs

      # - name: Set up Python 3.12
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.12'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Generate posts
      #   run: |
      #     python gen-comb.py ${{ github.ref_name }}

      # - name: Commit and push
      #   run: |
      #     git add -v content
      #     git config --global user.name $GIT_USERNAME
      #     git config --global user.email $GIT_EMAIL
      #     git commit -m "Update ${{ github.ref_name }}"
      #     git push

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.3'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: |
          cd hub
          hugo --minify

      - name: Deploy to organization repo
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          repo: DOL-CHS-MODS/hub
          build_dir: ./hub/public
          keep_history: false
          target_branch: gh-pages

      - name: Build netlify
        run: |
          cd hub
          rm -rf public
          sed -i 's#dol-chs-mods.github.io/hub/#dol-chs-mods-hub.netlify.app/#' config/_default/config.toml
          hugo --minify

      - name: Deploy to organization repo
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          repo: DOL-CHS-MODS/hub
          build_dir: ./hub/public
          keep_history: false
          target_branch: pages